spring:
  application:
    name: consul-user-service
  cloud:
    consul:
      host: 192.168.75.134
      port: 8500
      discovery:
        service-name: ${spring.application.name}
server:
  port: 8200
